### ISSUE TITLE
Add back volumes

### ISSUE THREAD

**Issue by jjti** [jjti/homelab#1]
```
        nomad_host_volumes:
          - name: root
            path: /
            owner: root
            group: bin
            mode: "0755"
            read_only: true
          - name: sata
            path: /mnt/sata
            owner: minio-user
            group: minio-user
            mode: "0755"
            read_only: false
          - name: seqq
            path: /var/lib/seqq/data
            owner: root
            group: root
            mode: "0755"
            read_only: false
          - name: arr-config-jellyfin
            path: /usr/local/var/config/jellyfin
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
          - name: arr-config-jellyseer
            path: /usr/local/var/config/jellyseer
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
          - name: arr-config-radarr
            path: /usr/local/var/config/radarr
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
          - name: arr-config-sonarr
            path: /usr/local/var/config/sonarr
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
          - name: arr-config-bazarr
            path: /usr/local/var/config/bazarr
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
          - name: arr-config-sabnzbd
            path: /usr/local/var/config/sabnzbd
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
          - name: arr-cache
            path: /usr/local/var/cache
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
          - name: arr-tv
            path: /usr/local/var/tv
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
          - name: arr-movies
            path: /usr/local/var/movies
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
          - name: arr-downloads
            path: /usr/local/var/downloads
            owner: josh
            group: josh
            mode: "0775"
            read_only: false
```
